name: Accessibility Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  accessibility-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run Accessibility Tests (Jest + axe)
      - name: Run accessibility tests
        run: |
          npm test -- --runInBand  # --runInBand ensures tests run sequentially to avoid timeouts

      # Step 5: Upload test results (optional, for logging)
      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: test-results/
